### ISSUE TITLE
 two or more field depend on one fields

### ISSUE THREAD

**Issue by nahidshaikh46** [rendezz/formbuilder_depends#2]
Hi,
can you upgrade for two or more field depend on one fields.
Thanks & Regards.

**Comment by rendezz** [comment]
Unfortunately I don't have much time right now so I won't be looking at this functionality.  But you can normally achieve the same by just chaining your depends.  A depends on B depends on C.  That is B is only seen if C is a value, then A is only seen if B is a value (and obviously seen, thats the chained dependency)
